ARG ELIXIR="1.14.2"
ARG ERLANG="25.1.2"
ARG ALPINE="3.16.2"

FROM "hexpm/elixir:${ELIXIR}-erlang-${ERLANG}-alpine-${ALPINE}"

RUN apk add build-base librsvg

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mkdir /app
WORKDIR /app

COPY . .

RUN mix deps.get --only test
RUN mix test
